#!/usr/bin/env bun
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createMcpBuildInfo } from "../packages/mcp/src/build-info.ts";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
export const MCP_PLUGIN_TARGETS = ["omp", "opencode", "dsh", "cursor", "codex", "kimi", "zcode"] as const;
export type McpPluginTarget = (typeof MCP_PLUGIN_TARGETS)[number];

function parseTarget(argv: string[]): McpPluginTarget {
  if (argv.length !== 2 || argv[0] !== "--target" || !MCP_PLUGIN_TARGETS.includes(argv[1] as McpPluginTarget)) {
    throw new Error(`usage: bun scripts/build-mcp-plugins.ts --target <${MCP_PLUGIN_TARGETS.join("|")}>`);
  }
  return argv[1] as McpPluginTarget;
}

function packageRoot(target: McpPluginTarget): string {
  return target === "omp" || target === "opencode" || target === "dsh"
    ? path.join(repoRoot, "packages", target)
    : repoRoot;
}

function outputDir(target: McpPluginTarget, root: string): string {
  return target === "omp" || target === "opencode" || target === "dsh"
    ? path.join(root, "mcp")
    : path.join(root, "mcp", "bundles", target, "dist", "mcp");
}

const GENERATED_BANNER =
  "// @generated by scripts/build-mcp-plugins.ts from packages/mcp/src/stdio.ts - do not edit; rebuild with `bun scripts/build-mcp-plugins.ts --target <target>`.\n";

function readVersion(file: string): string {
  const metadata = JSON.parse(readFileSync(path.join(repoRoot, file), "utf8")) as { version?: unknown };
  if (typeof metadata.version !== "string") throw new Error(`missing version in ${file}`);
  return metadata.version;
}

export async function buildMcpPlugin(target: McpPluginTarget): Promise<string> {
  const root = packageRoot(target);
  const output = outputDir(target, root);
  const sourceExecutable = path.join(repoRoot, "packages/mcp/dist/stdio.js");
  if (!existsSync(sourceExecutable)) throw new Error(`missing M4 server bundle: ${sourceExecutable}`);

  mkdirSync(output, { recursive: true });
  const bundle = readFileSync(sourceExecutable);
  const isConfigOnlyTarget = target !== "omp" && target !== "opencode" && target !== "dsh";
  writeFileSync(path.join(output, "stdio.js"), isConfigOnlyTarget
    ? Buffer.concat([Buffer.from(GENERATED_BANNER), bundle])
    : bundle);
  const buildInfo = createMcpBuildInfo(
    {
      pluginVersion: readVersion("package.json"),
      engineVersion: readVersion("packages/engine/package.json"),
      mcpVersion: readVersion("packages/mcp/package.json"),
    },
    target,
  );
  await Bun.write(path.join(output, "build-info.json"), `${JSON.stringify(buildInfo, null, 2)}\n`);

  if (!isConfigOnlyTarget) {
    const sourceConfigDir = path.join(repoRoot, "mcp");
    const configDir = path.join(root, "mcp");
    mkdirSync(configDir, { recursive: true });
    for (const filename of readdirSync(sourceConfigDir)) {
      if (filename.startsWith(`${target}-`) || filename === `${target}.json`) {
        cpSync(path.join(sourceConfigDir, filename), path.join(configDir, filename));
      }
    }
  }
  console.log(`build-mcp-plugins: ${target} -> ${path.relative(repoRoot, output)}`);

  return root;
}

async function main(): Promise<void> {
  await buildMcpPlugin(parseTarget(process.argv.slice(2)));
}

if (import.meta.main) {
  main().catch((error: unknown) => {
    console.error(`build-mcp-plugins: ${error instanceof Error ? error.message : error}`);
    process.exitCode = 1;
  });
}

