#!/usr/bin/env bun
import { build } from "bun";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createMcpBuildInfo, MCP_BUILD_INFO_FILENAME } from "../packages/mcp/src/build-info.ts";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
export const MCP_PLUGIN_TARGETS = ["omp", "opencode", "dsh", "cursor", "codex", "kimi", "zcode"] as const;
export type McpPluginTarget = (typeof MCP_PLUGIN_TARGETS)[number];

function parseTarget(argv: string[]): McpPluginTarget {
  if (argv.length !== 2 || argv[0] !== "--target" || !MCP_PLUGIN_TARGETS.includes(argv[1] as McpPluginTarget)) {
    throw new Error(`usage: bun scripts/build-mcp-plugins.ts --target <${MCP_PLUGIN_TARGETS.join("|")}>`);
  }
  return argv[1] as McpPluginTarget;
}

function outputDir(target: McpPluginTarget): string {
  return path.join(repoRoot, "mcp", "bundles", target, "dist", "mcp");
}

const GENERATED_BANNER =
  "// @generated by scripts/build-mcp-plugins.ts from packages/mcp/src/stdio.ts - do not edit; rebuild with `bun scripts/build-mcp-plugins.ts --target <target>`.\n";

function readVersion(file: string): string {
  const metadata = JSON.parse(readFileSync(path.join(repoRoot, file), "utf8")) as { version?: unknown };
  if (typeof metadata.version !== "string") throw new Error(`missing version in ${file}`);
  return metadata.version;
}

export async function buildMcpPlugin(target: McpPluginTarget): Promise<string> {
  const output = outputDir(target);
  mkdirSync(output, { recursive: true });
  const result = await build({
    entrypoints: [path.join(repoRoot, "packages/mcp/src/stdio.ts")],
    outdir: output,
    target: "node",
    packages: "bundle",
  });
  if (!result.success) {
    throw new Error(result.logs.map((entry) => entry.message).join("\n") || `failed to bundle ${target}`);
  }

  const bundlePath = path.join(output, "stdio.js");
  const bundle = readFileSync(bundlePath);
  writeFileSync(bundlePath, Buffer.concat([Buffer.from(GENERATED_BANNER), bundle]));
  const buildInfo = createMcpBuildInfo(
    {
      pluginVersion: readVersion("package.json"),
      engineVersion: readVersion("packages/engine/package.json"),
      mcpVersion: readVersion("packages/mcp/package.json"),
    },
    target,
  );
  await Bun.write(path.join(output, MCP_BUILD_INFO_FILENAME), `${JSON.stringify(buildInfo, null, 2)}\n`);
  console.log(`build-mcp-plugins: ${target} -> ${path.relative(repoRoot, output)}`);
  return output;
}

async function main(): Promise<void> {
  await buildMcpPlugin(parseTarget(process.argv.slice(2)));
}

if (import.meta.main) {
  main().catch((error: unknown) => {
    console.error(`build-mcp-plugins: ${error instanceof Error ? error.message : error}`);
    process.exitCode = 1;
  });
}

