/**
 * Dashboard asset generator — `bun run packages/cli/scripts/build-web.ts`.
 *
 * Bundles `web/app.ts` (Preact + htm, browser target) and reads
 * `web/shell.html` / `web/style.css`, then emits the ignored generated module
 * `src/dashboard/assets.generated.ts` exporting `dashboardHtml`, `dashboardJs`
 * and `dashboardCss` as escaped strings. The CLI build runs this before
 * bundling, so the published single artifact inlines the dashboard with no
 * disk asset directory, CDN, fonts or telemetry.
 *
 * Determinism: inputs are read from the repo only; no timestamp, random id or
 * absolute build path is embedded. Running the generator twice on unchanged
 * inputs produces byte-identical output (verified by the script itself after
 * each write via re-import and string equality).
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const cliRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const webDir = path.join(cliRoot, "web");
const outPath = path.join(cliRoot, "src", "dashboard", "assets.generated.ts");

const shellHtml = readFileSync(path.join(webDir, "shell.html"), "utf8");
const styleCss = readFileSync(path.join(webDir, "style.css"), "utf8");

const bundle = await Bun.build({
  entrypoints: [path.join(webDir, "app.ts")],
  target: "browser",
  minify: true,
});
if (!bundle.success) {
  console.error("build-web: app.ts bundle failed");
  for (const log of bundle.logs) console.error(String(log));
  process.exit(1);
}
const appJs = await bundle.outputs[0]!.text();

// Fixed asset references only; no disk asset directory is required at runtime.
if (!shellHtml.includes('"/assets/app.css"') || !shellHtml.includes('"/assets/app.js"')) {
  console.error('build-web: shell.html must reference fixed "/assets/app.css" and "/assets/app.js"');
  process.exit(1);
}
// Offline guard for resources a browser would actually fetch. The bundled JS
// is excluded: minified Preact carries a documentation URL string constant
// (error-message text), which is not a runtime fetch.
for (const [name, value] of [["html", shellHtml], ["css", styleCss]] as const) {
  if (/https?:\/\/|cdn\.|fonts\.googleapis/i.test(value)) {
    console.error(`build-web: dashboard ${name} embeds a remote/CDN reference; offline only`);
    process.exit(1);
  }
}

// JSON.stringify is a correct, deterministic string escaper for TS string
// literals (quotes, backslashes, control chars, line terminators all escaped).
// The CLI bundle misdecodes raw multi-byte UTF-8 in string literals
// (spec §7.4), so every non-ASCII code unit additionally becomes a \uXXXX
// escape — the generated module stays pure ASCII while the runtime string
// values (and the round-trip check below) are unchanged.
function toAsciiJsonLiteral(value: string): string {
  return JSON.stringify(value).replace(/[\u007f-\uffff]/g, (unit) =>
    `\\u${unit.charCodeAt(0).toString(16).padStart(4, "0")}`,
  );
}

const moduleSource = `// Generated by packages/cli/scripts/build-web.ts — do not edit.
// Regenerate with \`bun run packages/cli/scripts/build-web.ts\` (runs before every CLI build/prepublish).
export const dashboardHtml = ${toAsciiJsonLiteral(shellHtml)};

export const dashboardJs = ${toAsciiJsonLiteral(appJs)};

export const dashboardCss = ${toAsciiJsonLiteral(styleCss)};
`;

mkdirSync(path.dirname(outPath), { recursive: true });
writeFileSync(outPath, moduleSource, "utf8");

// Round-trip check: the generated module must import cleanly and reproduce the
// exact source strings (escape correctness + byte determinism of this run).
const generated = await import(pathToFileURL(outPath).href);
const roundTrips =
  generated.dashboardHtml === shellHtml &&
  generated.dashboardJs === appJs &&
  generated.dashboardCss === styleCss;
if (!roundTrips) {
  console.error("build-web: generated module does not round-trip the source strings");
  process.exit(1);
}

console.log(
  `build-web: wrote ${path.relative(cliRoot, outPath)} ` +
    `(html ${shellHtml.length}B, js ${appJs.length}B, css ${styleCss.length}B)`,
);
